resources:
  - url: http://127.0.0.1:5000/magiqtouch.js
    type: module
views:
  - cards:
      - type: custom:magiqtouch
        name: Boilerplate Card Development
        entity: sun.sun
        test_gui: true
